### ISSUE TITLE
Message should be parsed at the front-end

### ISSUE THREAD

**Issue by Sama34** [MyAlerts/Custom-Alerts-for-MyAlerts#3]
No text should be inserted into the DB after-parse, the text should be parsed when being showing to the user, on myalerts_alerts_output_start.

What if a MyCode is deleted or a new word was added to the word filter system?

**Comment by Shade-** [comment]
You're right Sama. I'll get a chance to look at this issue tomorrow, hopefully.

**Comment by Shade-** [comment]
Finally got the chance to get over it and fix it. Thank you @Sama34 for your contribution!
