### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by Destroy666x** [MyAlerts/Custom-Alerts-for-MyAlerts#4]
When sending alert to All Users I get this SQL error: 

MyBB has experienced an internal SQL error and cannot continue.

SQL Error:
1054 - Unknown column 'code' in 'where clause'
Query:
SELECT user_id FROM mybb_alert_setting_values WHERE code = 'custom'

(latest MyAlerts and Custom Alerts from github)

**Comment by Shade-** [comment]
It was a stupid error in the users selection process. Managed to fix it.
